name: tvkh

on:
  # schedule:
  #   - cron: '0 0,6,12,18 * * *'  
    
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-tvkh]

# concurrency:
#   group: n8n
#   cancel-in-progress: false
  
jobs:
  docker-compose:
    runs-on: ubuntu-latest
    env:
      R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
      R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      DB_PATH: ${{ secrets.DB_PATH }}
      TUNNEL_TOKEN: ${{ secrets.TUNNEL_TOKEN }}
      TS_CLIENT_ID: ${{ secrets.TS_CLIENT_ID }}
      TS_CLIENT_SECRET: ${{ secrets.TS_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
          
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GH_USERNAME }}
          password: ${{ secrets.MAC_GH_TOKEN }} 


  

      - name: Run docker-compose
        run: |
          docker compose up -d
          
          
      # - name: Free disk space
      #   run: |
      #     # sudo swapoff -a
      #     # sudo apt-get autoremove -y
      #     # sudo apt-get autoclean -y
      #     sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/lib/jvm /usr/share/swift /usr/local/.ghcup /usr/local/julia* /usr/local/share/chromium /opt/microsoft /opt/google /opt/az /usr/local/share/powershell
          

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          all_but_latest: true

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 86400 # 1 days

      - name: Do your work
        run: |
          sleep 5.8h
          
          
      - name: Trigger next run
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy-tvkh"}'

      - name: Do your work
        run: |
          sleep 1m
